// 1단계(추가 소스): 위키미디어 공용(카테고리·검색) + NASA 이미지 API 에서 후보 수집 → scripts/extra/candidates.json + 컨택트 시트
//   node scripts/extra/scan.mjs [sheet1,sheet2]   (인자 없으면 전부)
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
const UA = 'jigsawlab-catalog/0.1 (seabow2@nate.com)';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function json(url) { for (let i = 0; i < 3; i++) { try { const r = await fetch(url, { headers: { 'user-agent': UA } }); if (r.ok) return await r.json(); if (r.status === 429) await sleep(3000); } catch {} await sleep(800); } return null; }
const API = 'https://commons.wikimedia.org/w/api.php';
const OK_LIC = /^(Public domain|CC0|CC BY 4\.0|CC BY 3\.0|CC BY 2\.0|CC BY 2\.5)$/;
const strip = (s) => (s || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
/** 파일 제목 목록 → imageinfo (크기·라이선스·작가·설명·1600 썸네일) */
async function info(titles) {
  const out = [];
  for (let i = 0; i < titles.length; i += 40) {
    const d = await json(`${API}?action=query&titles=${encodeURIComponent(titles.slice(i, i + 40).join('|'))}&prop=imageinfo&iiprop=url|size|mime|extmetadata&iiurlwidth=1600&iiextmetadatalanguage=en&format=json`);
    for (const p of Object.values(d?.query?.pages ?? {})) { const ii = p.imageinfo?.[0]; if (!ii || !/jpeg|png|tiff/.test(ii.mime)) continue; const em = ii.extmetadata || {}; out.push({ title: p.title.slice(5), w: ii.width, h: ii.height, mime: ii.mime, lic: em.LicenseShortName?.value ?? '', artist: strip(em.Artist?.value), credit: strip(em.Credit?.value).slice(0, 200), date: strip(em.DateTimeOriginal?.value).replace(/date QS.*$/, '').trim().slice(0, 40), desc: strip(em.ImageDescription?.value).slice(0, 600), objName: strip(em.ObjectName?.value).slice(0, 120), url: ii.url, thumb: ii.thumburl, page: ii.descriptionurl }); }
    await sleep(200);
  }
  return out;
}
async function members(cat, type, limit) {
  let titles = [], cont = '';
  while (titles.length < limit) { const d = await json(`${API}?action=query&list=categorymembers&cmtitle=${encodeURIComponent('Category:' + cat)}&cmtype=${type}&cmlimit=100${cont}&format=json`); if (!d) break; titles.push(...(d.query?.categorymembers ?? []).map((m) => m.title)); if (!d.continue) break; cont = `&cmcontinue=${encodeURIComponent(d.continue.cmcontinue)}`; await sleep(200); }
  return titles.slice(0, limit);
}
/** 카테고리의 파일 + 하위 카테고리(한 단계) 파일 */
async function category(cat, limit = 200) {
  const titles = await members(cat, 'file', limit);
  for (const sub of (await members(cat, 'subcat', 30))) { if (titles.length >= limit) break; titles.push(...(await members(sub.slice(9), 'file', limit - titles.length))); }
  return [...new Set(titles)].slice(0, limit);
}
async function search(q, n = 10) { const d = await json(`${API}?action=query&list=search&srsearch=${encodeURIComponent(q)}&srnamespace=6&srlimit=${n}&format=json`); return (d?.query?.search ?? []).map((x) => x.title); }
async function nasa(q, n = 6) {
  const d = await json(`https://images-api.nasa.gov/search?q=${encodeURIComponent(q)}&media_type=image&page_size=${n}`); const out = [];
  for (const it of d?.collection?.items ?? []) { const m = it.data[0]; const c = await json(it.href); const files = (c || []).filter((u) => /~(orig|large)\.(jpg|jpeg|png|tif)$/i.test(u)); const large = files.find((u) => /~large\./.test(u)) ?? files[0]; if (!large) continue; out.push({ title: m.title, nasaId: m.nasa_id, date: (m.date_created || '').slice(0, 10), center: m.center, desc: (m.description || '').slice(0, 700), credit: m.secondary_creator || m.photographer || 'NASA', keywords: (m.keywords || []).slice(0, 8), url: large, thumb: it.links?.[0]?.href, page: `https://images.nasa.gov/details/${m.nasa_id}` }); await sleep(150); }
  return out;
}
// ── 수집 목록: 시트 → 항목. c: 카테고리, q: 검색(문구별 상위 후보), n: NASA 검색
const SHEETS = {
  korean: { c: ['Kim Hong-do', 'Shin Yun-bok', 'Hyewon pungsokdo', 'Jeong Seon', 'Minhwa', 'Paintings in the National Museum of Korea', 'Kim Deuk-sin', 'Jang Seung-eop', 'Yi Am', 'Chaekgeori', 'Irworobongdo', 'Paintings of the Joseon Dynasty', 'Korean paintings', 'Paintings in the Leeum, Samsung Museum of Art', 'Paintings in the Kansong Art Museum'], minW: 1000 },
  masters: { q: ['Rembrandt The Night Watch Rijksmuseum', 'Velázquez Las Meninas Prado', 'Van Eyck Arnolfini Portrait', 'Bruegel Tower of Babel Vienna', 'Bosch Garden of Earthly Delights', 'Delacroix Liberty Leading the People', 'Friedrich Wanderer above the Sea of Fog', 'Whistler Arrangement in Grey and Black Mother', 'Fragonard The Swing Wallace', 'Millais Ophelia Tate', 'Waterhouse Lady of Shalott 1888', 'Van Gogh Sunflowers National Gallery London', 'Van Gogh Café Terrace at Night', 'Van Gogh Irises Getty', 'Van Gogh Starry Night Over the Rhône', 'Van Gogh Wheatfield with Crows', 'Rousseau The Sleeping Gypsy', 'Rousseau The Dream 1910', 'Klimt Portrait of Adele Bloch-Bauer I', 'Renoir Luncheon of the Boating Party', 'Manet A Bar at the Folies-Bergère', 'Degas The Dance Class Orsay', 'Monet Woman with a Parasol', 'Monet Japanese Footbridge', 'Constable The Hay Wain', 'Turner The Fighting Temeraire', 'Botticelli Primavera Uffizi', 'Raphael School of Athens', 'Leonardo The Last Supper', 'Seurat Bathers at Asnières', 'Seurat The Circus', 'David Napoleon Crossing the Alps', 'Vermeer View of Delft', 'Vermeer The Art of Painting', 'Vermeer The Little Street', 'Bruegel The Harvesters Met', 'Bruegel Peasant Wedding', 'Goya The Parasol', 'Leighton Flaming June', 'Alma-Tadema Roses of Heliogabalus', 'Arcimboldo Vertumnus', 'Klimt Tree of Life Stoclet', 'Rembrandt Storm on the Sea of Galilee', 'Caravaggio Basket of Fruit', 'Bosschaert Bouquet of Flowers in a Glass Vase', 'Aivazovsky The Ninth Wave', 'Sorolla Walk on the Beach', 'Cassatt The Boating Party', 'Homer Breezing Up', 'Bierstadt Among the Sierra Nevada', 'Cole The Oxbow', 'Canaletto Grand Canal Salute', 'Pissarro Boulevard Montmartre at Night', 'Caillebotte Le Pont de l\'Europe', 'Hiroshige Plum Garden at Kameido', 'Hokusai Kajikazawa in Kai Province', 'Audubon American Flamingo', 'Audubon Wild Turkey', 'Klimt The Kiss'.replace('The Kiss', 'Judith I'), 'Larsson Breakfast under the Big Birch', 'Monet Poppies Argenteuil', 'Renoir Dance at Bougival', 'Gauguin Vision after the Sermon', 'Cézanne Mont Sainte-Victoire', 'Manet Le Déjeuner sur l\'herbe', 'Vermeer Girl Reading a Letter at an Open Window', 'Hammershøi Interior', 'Böcklin Isle of the Dead', 'Waterhouse Hylas and the Nymphs', 'Munch The Sun Oslo', 'Hokusai Ejiri in Suruga', 'Hiroshige Kambara', 'Van Gogh Almond Blossom'.replace('Almond Blossom', 'The Bedroom Arles Orsay')], minW: 1500 },
  photochrom: { c: ['Featured photochrom pictures', 'Photochrom Travel Views', 'Tokyo on photochrome prints'], minW: 1500 },
  photochrom2: { c: ['Photochrom prints collection (Italy)', 'Photochrom prints collection (France)', 'Photochrom prints collection (Germany)', 'Photochrom prints collection (Turkey)', 'Photochrom prints collection (Jerusalem)'], minW: 1500, max: 60 },
  masters2: { q: ['Sargent Carnation, Lily, Lily, Rose', 'Cassatt Little Girl in a Blue Armchair', 'Monet Bridge over a Pond of Water Lilies Met', 'Monet Garden at Sainte-Adresse', 'Renoir The Umbrellas National Gallery', 'Van Gogh The Night Café Yale', 'Klimt Beech Grove I', 'Klimt Farm Garden with Sunflowers', 'Millet The Angelus', 'Frans Hals Laughing Cavalier', 'Titian Bacchus and Ariadne', 'Raphael Sistine Madonna', 'Michelangelo Creation of Adam', 'Turner Rain, Steam and Speed', 'Monet San Giorgio Maggiore at Dusk', 'Mucha Zodiac 1896', 'Mucha The Seasons 1896', 'Vermeer The Lacemaker', 'Monet Rouen Cathedral Sunlight', 'Renoir Girl with a Watering Can', 'Bruegel Netherlandish Proverbs', 'Monet The Magpie', 'Sisley Snow at Louveciennes', 'Klimt Attersee', 'Kandinsky Composition VII', 'Rousseau Surprised Tiger in a Tropical Storm', 'Hokusai Umegawa in Sagami Province', 'Hokusai Suspension Bridge Hida Etchu', 'Van Gogh Fishing Boats on the Beach at Saintes-Maries', 'Van Gogh Vase with Fifteen Sunflowers Amsterdam', 'Klimt Water Serpents', 'Monet Regatta at Argenteuil', 'Monet The Artist\'s Garden at Giverny', 'Morisot The Cradle', 'Caillebotte The Floor Scrapers', 'Böcklin', 'Ilya Repin Barge Haulers on the Volga', 'Shishkin Morning in a Pine Forest', 'Kuindzhi Moonlit Night on the Dnieper', 'Levitan Golden Autumn', 'Hokusai Great Wave'.replace('Great Wave', 'Cranes from Quick Lessons'), 'Ito Jakuchu Rooster', 'Ogata Korin Irises screen', 'Tawaraya Sotatsu Wind God Thunder God', 'Utamaro Three Beauties of the Present Day', 'Hasegawa Tohaku Pine Trees', 'Kano Eitoku Cypress', 'Ohara Koson', 'Qing dynasty painting', 'Zhang Zeduan Along the River During the Qingming Festival', 'Redouté Roses', 'Ernst Haeckel Kunstformen der Natur', 'Alphonse Mucha Job 1896', 'Gauguin Tahitian Women on the Beach', 'Gauguin Where Do We Come From', 'Millais The Blind Girl', 'Rossetti Proserpine', 'Burne-Jones The Golden Stairs', 'Vigée Le Brun Self-portrait Straw Hat', 'Gainsborough Blue Boy', 'Hopper', 'Carl Larsson Christmas Eve', 'Anders Zorn Midsummer Dance', 'Peder Severin Krøyer Summer Evening on Skagen', 'Krøyer Hip Hip Hurrah', 'Hammershøi'], minW: 1500 },
  photo: { q: ['photochrom Venice Grand Canal', 'photochrom Neuschwanstein', 'photochrom Matterhorn Zermatt', 'photochrom Norway fjord', 'photochrom Cairo pyramids Sphinx', 'photochrom Constantinople Bosphorus', 'photochrom Japan', 'photochrom Niagara Falls', 'photochrom Yosemite', 'photochrom Paris Eiffel Tower', 'photochrom London Tower Bridge', 'photochrom Giant\'s Causeway', 'photochrom Rhine castle', 'photochrom New York Brooklyn Bridge', 'photochrom Chicago', 'photochrom Grand Canyon', 'photochrom Yellowstone', 'photochrom Rome Colosseum', 'photochrom Naples Vesuvius', 'photochrom Capri', 'photochrom Algiers', 'photochrom Lucerne', 'photochrom Edinburgh', 'photochrom Moscow Kremlin', 'photochrom Nice', 'photochrom Monte Carlo', 'photochrom Florida', 'photochrom Alaska', 'photochrom Mont Saint-Michel', 'photochrom Amalfi', 'photochrom Dresden', 'photochrom Heidelberg', 'photochrom Chillon', 'photochrom Interlaken Jungfrau', 'photochrom Rigi', 'photochrom Geneva', 'photochrom Mostar', 'photochrom Dubrovnik Ragusa', 'photochrom Sarajevo', 'photochrom Athens Acropolis', 'photochrom Damascus', 'photochrom Beirut', 'photochrom Tunis', 'photochrom Zanzibar', 'photochrom Ceylon', 'photochrom India', 'photochrom Hawaii', 'photochrom San Francisco', 'photochrom Washington Capitol', 'photochrom Boston', 'photochrom Quebec', 'photochrom Banff', 'photochrom Mexico', 'photochrom Cuba Havana', 'photochrom Stockholm', 'photochrom Copenhagen', 'photochrom Amsterdam', 'photochrom Bruges', 'photochrom Brussels Grand Place', 'photochrom Vienna', 'photochrom Prague', 'photochrom Budapest', 'photochrom Salzburg', 'photochrom Innsbruck', 'photochrom Verona', 'photochrom Milan Cathedral', 'photochrom Florence', 'photochrom Pisa', 'photochrom Genoa', 'photochrom Lake Como', 'photochrom Lake Garda', 'photochrom Sicily Taormina', 'photochrom Malta', 'photochrom Lisbon', 'photochrom Seville', 'photochrom Granada Alhambra', 'photochrom Toledo', 'photochrom Barcelona', 'photochrom Mallorca', 'photochrom Killarney', 'photochrom Dublin', 'photochrom Blarney', 'photochrom Oxford', 'photochrom Windsor', 'photochrom Isle of Wight', 'photochrom Lake District', 'photochrom Scotland Loch', 'photochrom Wales', 'photochrom Cornwall'], minW: 1500 },
  space2: { q: ['Pillars of Creation NIRCam Webb', 'Cosmic Cliffs Carina Nebula Webb NIRCam', 'Crab Nebula Hubble mosaic', 'Helix Nebula Hubble NGC 7293', 'Andromeda Galaxy M31 Hubble', 'Whirlpool Galaxy M51 Hubble', 'Sombrero Galaxy M104 Hubble', 'Horsehead Nebula Hubble infrared', 'Orion Nebula Hubble mosaic', 'Earthrise Apollo 8 NASA', 'The Blue Marble Apollo 17', 'Saturn Cassini equinox', 'Jupiter Juno JunoCam', 'Butterfly Nebula NGC 6302 Hubble', "Cat's Eye Nebula NGC 6543 Hubble", 'Lagoon Nebula Hubble 2018', 'Southern Ring Nebula Webb', "Stephan's Quintet Webb", 'Cartwheel Galaxy Webb', 'Mystic Mountain Carina Hubble', 'Bubble Nebula NGC 7635 Hubble', 'Veil Nebula Hubble', 'Ring Nebula Webb NIRCam', 'Buzz Aldrin Apollo 11 NASA', 'Curiosity rover selfie Mars', 'Aurora from ISS NASA', 'Tarantula Nebula Webb', 'Eagle Nebula Hubble', 'Westerlund 2 Hubble', 'Antennae Galaxies Hubble', 'Pinwheel Galaxy M101 Hubble', 'Rosette Nebula', 'Hubble Ultra Deep Field', 'Webb Deep Field SMACS 0723', 'Phantom Galaxy M74 Webb', 'Pluto New Horizons', 'Neptune Voyager 2', 'Uranus Webb rings', 'Mars Valles Marineris Viking', 'Moon full NASA LRO', 'Solar flare SDO sun', 'Earth at night NASA Black Marble', 'Milky Way panorama ESO', 'Eta Carinae Hubble', 'Cone Nebula Hubble', 'Sun SDO ultraviolet', 'International Space Station NASA', 'Saturn hexagon Cassini', 'Jupiter Great Red Spot Juno', 'NGC 602 Hubble', 'Omega Nebula Hubble', 'Trifid Nebula', 'Pleiades'], minW: 1500 },
  // ── 고양이와 강아지: 회화·판화만(사진 제외 — 작품마다 이야기를 붙이는 사이트 성격에 맞추고 라이선스도 단순하게)
  pets: { c: ['Paintings of cats', 'Kittens in art', 'Cats in art of Japan', 'Cats by Utagawa Kuniyoshi', 'Louis Wain', 'Henri\u00ebtte Ronner-Knip', 'Arthur Heyer', 'Julius Adam', 'Carl Reichert (painter)', 'Charles van den Eycken', 'Th\u00e9ophile Alexandre Steinlen', 'Paintings of dogs', 'Charles Burton Barber', 'Cecil Aldin', 'John Emms', 'Maud Earl', 'Edwin Landseer', 'Alfred Dedreux', 'Philip Reinagle'], minW: 1300, max: 80 },
  // ── 동화와 판타지 삽화(황금기). 카이 닐센(1957 몰)은 아직 보호 중일 수 있어 뺐다
  tale: { c: ['Arthur Rackham', 'Ivan Bilibin', 'Edmund Dulac', 'Walter Crane', 'Warwick Goble', 'John Bauer', 'Viktor Vasnetsov', 'Mikhail Vrubel', 'Kate Greenaway', 'Randolph Caldecott', 'John Anster Fitzgerald', 'Fairies in art', 'Edward Robert Hughes', 'Joseph Noel Paton', 'Elsa Beskow', 'Theodor Kittelsen', 'Harry Clarke', 'Charles Robinson', 'Jessie Willcox Smith', 'Virginia Frances Sterrett', 'Sophie Gengembre Anderson', 'Aubrey Beardsley'], minW: 1300, max: 80 },
  space: { n: ['Pillars of Creation Webb', 'Carina Nebula Cosmic Cliffs Webb', 'Crab Nebula Hubble', 'Helix Nebula', 'Andromeda galaxy Hubble', 'Whirlpool Galaxy M51', 'Sombrero Galaxy', 'Horsehead Nebula Hubble', 'Orion Nebula Hubble', 'Earthrise Apollo 8', 'Blue Marble Apollo 17', 'Saturn Cassini portrait', 'Jupiter Juno', 'Butterfly Nebula', "Cat's Eye Nebula", 'Lagoon Nebula Hubble', 'Southern Ring Nebula Webb', "Stephan's Quintet Webb", 'Cartwheel Galaxy Webb', 'Mystic Mountain Hubble', 'Bubble Nebula Hubble', 'Veil Nebula Hubble', 'Ring Nebula Webb', 'Buzz Aldrin Apollo 11 moon', 'Mars Curiosity panorama', 'Aurora ISS', 'Tarantula Nebula Webb', 'Eagle Nebula', 'Westerlund 2', 'Antennae Galaxies'] },
};
const only = (process.argv[2] || '').split(',').filter(Boolean);
const prev = existsSync('scripts/extra/candidates.json') ? JSON.parse(readFileSync('scripts/extra/candidates.json', 'utf8')) : {};
const out = { ...prev };
for (const [sheet, cfg] of Object.entries(SHEETS)) {
  if (only.length && !only.includes(sheet)) continue;
  let list = [];
  if (cfg.n) { for (const q of cfg.n) { const r = await nasa(q); r.forEach((x) => (x.q = q)); list.push(...r); process.stdout.write(`${sheet}/${q}: ${r.length}\n`); } }
  else {
    const seen = new Set();
    if (cfg.c) for (const c of cfg.c) { const titles = await category(c, cfg.max ?? 200); const inf = await info(titles); let n = 0; for (const x of inf) { if (seen.has(x.title)) continue; if (!OK_LIC.test(x.lic) || Math.max(x.w, x.h) < cfg.minW) continue; const asp = x.w / x.h; if (asp < 0.5 || asp > 2.2) continue; seen.add(x.title); x.q = c; list.push(x); n++; } process.stdout.write(`${sheet}/${c}: ${titles.length} → ${n}\n`); }
    if (cfg.q) for (const q of cfg.q) { const titles = await search(q, 8); const inf = await info(titles); const good = inf.filter((x) => OK_LIC.test(x.lic) && Math.max(x.w, x.h) >= cfg.minW && x.w / x.h > 0.4 && x.w / x.h < 2.3).sort((a, b) => b.w * b.h - a.w * a.h).slice(0, 3); for (const x of good) { if (seen.has(x.title)) continue; seen.add(x.title); x.q = q; list.push(x); } process.stdout.write(`${sheet}/${q}: ${inf.length} → ${good.length}\n`); }
  }
  out[sheet] = list;
  const html = `<!doctype html><meta charset=utf-8><style>body{margin:0;background:#111;color:#eee;font:11px sans-serif}.g{display:grid;grid-template-columns:repeat(8,1fr);gap:4px;padding:4px}.c{background:#222;padding:3px}.c img{width:100%;aspect-ratio:1;object-fit:cover;display:block}.c div{height:3.9em;overflow:hidden;line-height:1.3}b{color:#ffd54a}i{color:#7fd}</style><h2 style="margin:6px">${sheet} (${list.length})</h2><div class=g>${list.map((o, i) => `<div class=c><img src="${o.thumb ? o.thumb.replace(/\/1600px-/, '/320px-') : ''}" loading="lazy"><div><b>${i}</b> <i>${o.w}×${o.h}</i> ${(o.q || '').slice(0, 30)} · ${(o.title || '').slice(0, 50)}</div></div>`).join('')}</div>`;
  writeFileSync(`scripts/extra/sheet-${sheet}.html`, html);
}
writeFileSync('scripts/extra/candidates.json', JSON.stringify(out, null, 1));
console.log('total', Object.entries(out).map(([k, v]) => `${k}:${v.length}`).join(' '));
