// 2단계(추가 소스): 컨택트 시트에서 고른 항목 → 제목·작가·소장처를 붙여 selected.json
//   항목: { s: 시트, i: 번호 | t: 파일 제목, key, cat, title(영문), artist(영문), date, year, museum, medium?, credit? }
import { readFileSync, writeFileSync } from 'node:fs';
const C = JSON.parse(readFileSync('scripts/extra/candidates.json', 'utf8'));
export const MUSEUMS = {
  nmk: ['국립중앙박물관', 'National Museum of Korea', '国立中央博物館'], kansong: ['간송미술관', 'Kansong Art Museum', '澗松美術館'], leeum: ['리움미술관', 'Leeum Museum of Art', 'リウム美術館'],
  cma: ['클리블랜드 미술관', 'Cleveland Museum of Art', 'クリーブランド美術館'], hoam: ['호암미술관', 'Ho-Am Art Museum', '湖巌美術館'], philadelphia: ['필라델피아 미술관', 'Philadelphia Museum of Art', 'フィラデルフィア美術館'],
  rijks: ['암스테르담 국립미술관', 'Rijksmuseum, Amsterdam', 'アムステルダム国立美術館'], prado: ['프라도 미술관', 'Museo del Prado, Madrid', 'プラド美術館'], louvre: ['루브르 박물관', 'Musée du Louvre, Paris', 'ルーヴル美術館'],
  ngl: ['런던 내셔널 갤러리', 'National Gallery, London', 'ロンドン・ナショナル・ギャラリー'], orsay: ['오르세 미술관', 'Musée d\'Orsay, Paris', 'オルセー美術館'], tate: ['테이트 브리튼', 'Tate Britain, London', 'テート・ブリテン'],
  getty: ['게티 센터', 'J. Paul Getty Museum, Los Angeles', 'ゲティ・センター'], nga: ['워싱턴 국립미술관', 'National Gallery of Art, Washington', 'ワシントン・ナショナル・ギャラリー'], met: ['메트로폴리탄 미술관', 'The Metropolitan Museum of Art, New York', 'メトロポリタン美術館'],
  moma: ['뉴욕 현대미술관', 'Museum of Modern Art, New York', 'ニューヨーク近代美術館'], uffizi: ['우피치 미술관', 'Uffizi Gallery, Florence', 'ウフィツィ美術館'], hamburg: ['함부르크 미술관', 'Hamburger Kunsthalle', 'ハンブルク美術館'],
  wallace: ['월리스 컬렉션', 'The Wallace Collection, London', 'ウォレス・コレクション'], neue: ['노이에 갤러리', 'Neue Galerie, New York', 'ノイエ・ガレリエ'], phillips: ['필립스 컬렉션', 'The Phillips Collection, Washington', 'フィリップス・コレクション'],
  courtauld: ['코톨드 갤러리', 'The Courtauld Gallery, London', 'コートールド・ギャラリー'], mauritshuis: ['마우리츠하위스', 'Mauritshuis, The Hague', 'マウリッツハイス美術館'], khm: ['빈 미술사 박물관', 'Kunsthistorisches Museum, Vienna', 'ウィーン美術史美術館'],
  vatican: ['바티칸 박물관', 'Vatican Museums', 'ヴァチカン美術館'], grazie: ['산타 마리아 델레 그라치에 수도원', 'Santa Maria delle Grazie, Milan', 'サンタ・マリア・デッレ・グラツィエ修道院'], vgm: ['반 고흐 미술관', 'Van Gogh Museum, Amsterdam', 'ゴッホ美術館'],
  km: ['크뢸러 뮐러 미술관', 'Kröller-Müller Museum, Otterlo', 'クレラー・ミュラー美術館'], hermitage: ['에르미타주 미술관', 'State Hermitage Museum, St Petersburg', 'エルミタージュ美術館'], rusmus: ['러시아 미술관', 'State Russian Museum, St Petersburg', 'ロシア美術館'],
  ponce: ['폰세 미술관', 'Museo de Arte de Ponce', 'ポンセ美術館'], mfa: ['보스턴 미술관', 'Museum of Fine Arts, Boston', 'ボストン美術館'], saam: ['스미스소니언 미국미술관', 'Smithsonian American Art Museum', 'スミソニアン・アメリカ美術館'],
  ambrosiana: ['암브로시아나 미술관', 'Pinacoteca Ambrosiana, Milan', 'アンブロジアーナ絵画館'], skokloster: ['스코클로스테르 성', 'Skokloster Castle, Sweden', 'スコークロステル城'], mak: ['빈 응용미술관', 'MAK, Vienna', 'ウィーン応用美術館'],
  gardner: ['이사벨라 스튜어트 가드너 미술관', 'Isabella Stewart Gardner Museum, Boston', 'イザベラ・スチュワート・ガードナー美術館'], sorolla: ['소로야 미술관', 'Museo Sorolla, Madrid', 'ソローリャ美術館'], nmsw: ['스웨덴 국립미술관', 'Nationalmuseum, Stockholm', 'スウェーデン国立美術館'],
  dresden: ['드레스덴 고전거장회화관', 'Gemäldegalerie Alte Meister, Dresden', 'ドレスデン国立古典絵画館'], basel: ['바젤 미술관', 'Kunstmuseum Basel', 'バーゼル市立美術館'], manchester: ['맨체스터 미술관', 'Manchester Art Gallery', 'マンチェスター美術館'],
  belvedere: ['벨베데레 미술관', 'Belvedere, Vienna', 'ベルヴェデーレ宮殿'], loc: ['미국 의회도서관', 'Library of Congress', 'アメリカ議会図書館'],
  nasa: ['NASA', 'NASA', 'NASA'], hubble: ['NASA / ESA 허블 우주망원경', 'NASA / ESA Hubble Space Telescope', 'NASA / ESA ハッブル宇宙望遠鏡'], webb: ['NASA / ESA / CSA 제임스 웹 우주망원경', 'NASA / ESA / CSA James Webb Space Telescope', 'NASA / ESA / CSA ジェイムズ・ウェッブ宇宙望遠鏡'], jpl: ['NASA / JPL', 'NASA / JPL', 'NASA / JPL'],
  cbl: ['체스터 비티 도서관', 'Chester Beatty, Dublin', 'チェスター・ビーティー図書館'], audubon: ['오듀본 《아메리카의 새》', 'Audubon, The Birds of America', 'オーデュボン『アメリカの鳥類』'], ngs: ['스코틀랜드 국립미술관', 'National Galleries of Scotland, Edinburgh', 'スコットランド国立美術館'],
  bma: ['볼티모어 미술관', 'Baltimore Museum of Art', 'ボルティモア美術館'], berlin: ['베를린 구 국립미술관', 'Alte Nationalgalerie, Berlin', 'ベルリン旧国立美術館'], berlingg: ['베를린 국립회화관', 'Gemäldegalerie, Berlin', 'ベルリン絵画館'],
  uio: ['오슬로 대학교', 'University of Oslo', 'オスロ大学'], yale: ['예일 대학교 미술관', 'Yale University Art Gallery', 'イェール大学美術館'], dresdennm: ['드레스덴 신거장회화관', 'Galerie Neue Meister, Dresden', 'ドレスデン新絵画館'],
  cardiff: ['웨일스 국립박물관', 'National Museum Cardiff', 'ウェールズ国立博物館'], bnf: ['프랑스 국립도서관', 'Bibliothèque nationale de France', 'フランス国立図書館'], leopold: ['레오폴트 미술관', 'Leopold Museum, Vienna', 'レオポルド美術館'],
  tretyakov: ['트레티야코프 미술관', 'Tretyakov Gallery, Moscow', 'トレチャコフ美術館'], kenninji: ['겐닌지 (교토)', 'Kennin-ji, Kyoto', '建仁寺（京都）'], tnm: ['도쿄 국립박물관', 'Tokyo National Museum', '東京国立博物館'],
  pmbeijing: ['베이징 고궁박물원', 'Palace Museum, Beijing', '北京故宮博物院'], bmag: ['버밍엄 미술관', 'Birmingham Museum and Art Gallery', 'バーミンガム美術館'], huntington: ['헌팅턴 도서관·미술관', 'The Huntington, San Marino', 'ハンティントン図書館'],
  skagen: ['스카겐 미술관', 'Skagens Museum', 'スケーエン美術館'], gothenburg: ['예테보리 미술관', 'Gothenburg Museum of Art', 'ヨーテボリ美術館'], randers: ['라네르스 미술관', 'Randers Museum of Art', 'ラナース美術館'], private: ['개인 소장', 'Private collection', '個人蔵'], npm: ['국립고궁박물관', 'National Palace Museum of Korea', '国立古宮博物館'], commons: ['위키미디어 공용', 'Wikimedia Commons', 'ウィキメディア・コモンズ'], mfah: ['휴스턴 미술관', 'Museum of Fine Arts, Houston', 'ヒューストン美術館'],
  detroit: ['디트로이트 미술관', 'Detroit Institute of Arts', 'デトロイト美術館'], oslo: ['오슬로 국립미술관', 'National Museum, Oslo', 'オスロ国立美術館'], kmm: ['크뢸러 뮐러 미술관', 'Kröller-Müller Museum, Otterlo', 'クレラー・ミュラー美術館'],
};
// 문자열 소장처는 그대로(3언어 동일)
const P = [];
const add = (s, picks) => { for (const p of picks) P.push({ s, ...p }); };
// ── 한국 회화 (국립중앙박물관 e뮤지엄 스캔 등, PD)
add('korean', [
  { i: 85, key: 'danwon-seodang', cat: 'korean', title: 'Seodang (Village School)', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 87, key: 'danwon-bballaeteo', cat: 'korean', title: 'Washing Place', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 88, key: 'danwon-byeotajak', cat: 'korean', title: 'Threshing Rice', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 89, key: 'danwon-giwaigi', cat: 'korean', title: 'Tiling a Roof', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 90, key: 'danwon-daejanggan', cat: 'korean', title: 'The Smithy', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 91, key: 'danwon-hwalssogi', cat: 'korean', title: 'Archery Practice', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 97, key: 'danwon-jumak', cat: 'korean', title: 'Tavern', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 96, key: 'danwon-jeomsim', cat: 'korean', title: 'Lunch in the Field', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 95, key: 'danwon-umulga', cat: 'korean', title: 'At the Well', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 94, key: 'danwon-gilssam', cat: 'korean', title: 'Weaving', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 104, key: 'danwon-naruteo', cat: 'korean', title: 'Ferry Landing', artist: 'Kim Hong-do', date: 'c. 1780', year: 1780, museum: 'nmk' },
  { i: 168, key: 'jeongseon-inwang', cat: 'korean', title: 'Clearing after Rain on Mount Inwang', artist: 'Jeong Seon', date: '1751', year: 1751, museum: 'nmk' },
  { i: 167, key: 'jeongseon-geumgang', cat: 'korean', title: 'Complete View of Mount Geumgang', artist: 'Jeong Seon', date: '1734', year: 1734, museum: 'leeum' },
  { i: 147, key: 'hyewon-ssanggeom', cat: 'korean', title: 'Double Sword Dance', artist: 'Shin Yun-bok', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 153, key: 'hyewon-wolha', cat: 'korean', title: 'Lovers under the Moon', artist: 'Shin Yun-bok', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 150, key: 'hyewon-yeonso', cat: 'korean', title: 'Spring Outing of Young Nobles', artist: 'Shin Yun-bok', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 130, key: 'hyewon-juyu', cat: 'korean', title: 'Boating on a Clear River', artist: 'Shin Yun-bok', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 129, key: 'hyewon-jusa', cat: 'korean', title: 'Drinking at a Tavern', artist: 'Shin Yun-bok', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 146, key: 'hyewon-sangchun', cat: 'korean', title: 'Spring Evening Party', artist: 'Shin Yun-bok', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 131, key: 'hyewon-cheonggeum', cat: 'korean', title: 'Listening to the Geomungo by the Lotus Pond', artist: 'Shin Yun-bok', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 200, key: 'geungjae-pajeok', cat: 'animal', title: 'Breaking the Silence (Cat Stealing a Chick)', artist: 'Kim Deuk-sin', date: 'c. 1780', year: 1800, museum: 'kansong' },
  { i: 224, key: 'chaekgeori-yitaekgyun', cat: 'korean', title: 'Books and Scholars\' Accouterments (Chaekgeori)', artist: 'Yi Taek-gyun', date: '1875', year: 1875, museum: 'cma' },
  { i: 232, key: 'anjungsik-seongjae', cat: 'korean', title: 'Seongjaesugan (Scholar\'s Retreat)', artist: 'An Jung-sik', date: '1910', year: 1910, museum: 'private' },
  { i: 179, key: 'minhwa-tiger-magpie', cat: 'korean', title: 'Tiger and Magpie (Minhwa)', artist: 'Unknown Korean artist', date: 'c. 1850', year: 1850, museum: 'private' },
  { i: 198, key: 'jojiun-crane-pine', cat: 'animal', title: 'Crane and Pine', artist: 'Jo Ji-un', date: 'c. 1630', year: 1650, museum: 'nmk' },
  { i: 238, key: 'hwajodo-screen', cat: 'korean', title: 'Birds and Flowers (Ten-panel Screen)', artist: 'Unknown Korean artist', date: 'c. 1900', year: 1900, museum: 'met' },
  { t: 'Irworobongdo.jpg', key: 'irworobongdo', cat: 'korean', title: 'Irworobongdo (Sun, Moon and Five Peaks)', artist: 'Unknown Korean artist', date: 'c. 1800', year: 1800, museum: 'npm' },
  { t: '창덕6447 십장생도 병풍.jpg', key: 'sipjangsaengdo', cat: 'korean', title: 'Ten Symbols of Longevity (Sipjangsaengdo)', artist: 'Unknown Korean artist', date: 'c. 1850', year: 1850, museum: 'npm' },
]);
// ── 서양·동양 명화 (위키미디어 공용, PD)
add('masters', [
  { i: 2, key: 'night-watch', cat: 'masters', title: 'The Night Watch', artist: 'Rembrandt van Rijn', date: '1642', year: 1642, museum: 'rijks' },
  { i: 4, key: 'las-meninas', cat: 'masters', title: 'Las Meninas', artist: 'Diego Velázquez', date: '1656', year: 1656, museum: 'prado' },
  { i: 7, key: 'arnolfini', cat: 'masters', title: 'The Arnolfini Portrait', artist: 'Jan van Eyck', date: '1434', year: 1434, museum: 'ngl' },
  { i: 10, key: 'tower-babel', cat: 'masters', title: 'The Tower of Babel', artist: 'Pieter Bruegel the Elder', date: '1563', year: 1563, museum: 'khm' },
  { i: 12, key: 'garden-delights', cat: 'masters', title: 'The Garden of Earthly Delights', artist: 'Hieronymus Bosch', date: 'c. 1490–1510', year: 1500, museum: 'prado' },
  { i: 15, key: 'liberty', cat: 'masters', title: 'Liberty Leading the People', artist: 'Eugène Delacroix', date: '1830', year: 1830, museum: 'louvre' },
  { i: 18, key: 'wanderer', cat: 'masters', title: 'Wanderer above the Sea of Fog', artist: 'Caspar David Friedrich', date: 'c. 1818', year: 1818, museum: 'hamburg' },
  { i: 21, key: 'whistler-mother', cat: 'masters', title: 'Arrangement in Grey and Black No. 1 (Whistler\'s Mother)', artist: 'James McNeill Whistler', date: '1871', year: 1871, museum: 'orsay' },
  { i: 24, key: 'swing', cat: 'masters', title: 'The Swing', artist: 'Jean-Honoré Fragonard', date: '1767', year: 1767, museum: 'wallace' },
  { i: 26, key: 'ophelia', cat: 'masters', title: 'Ophelia', artist: 'John Everett Millais', date: '1851–52', year: 1852, museum: 'tate' },
  { i: 30, key: 'shalott', cat: 'masters', title: 'The Lady of Shalott', artist: 'John William Waterhouse', date: '1888', year: 1888, museum: 'tate' },
  { i: 31, key: 'sunflowers', cat: 'masters', title: 'Sunflowers', artist: 'Vincent van Gogh', date: '1888', year: 1888, museum: 'ngl' },
  { i: 34, key: 'cafe-terrace', cat: 'masters', title: 'Café Terrace at Night', artist: 'Vincent van Gogh', date: '1888', year: 1888, museum: 'km' },
  { i: 37, key: 'irises', cat: 'masters', title: 'Irises', artist: 'Vincent van Gogh', date: '1889', year: 1889, museum: 'getty' },
  { i: 40, key: 'rhone', cat: 'masters', title: 'Starry Night Over the Rhône', artist: 'Vincent van Gogh', date: '1888', year: 1888, museum: 'orsay' },
  { i: 43, key: 'wheatfield-crows', cat: 'landscape', title: 'Wheatfield with Crows', artist: 'Vincent van Gogh', date: '1890', year: 1890, museum: 'vgm' },
  { i: 49, key: 'rousseau-dream', cat: 'masters', title: 'The Dream', artist: 'Henri Rousseau', date: '1910', year: 1910, museum: 'moma' },
  { i: 53, key: 'adele', cat: 'masters', title: 'Portrait of Adele Bloch-Bauer I', artist: 'Gustav Klimt', date: '1907', year: 1907, museum: 'neue' },
  { i: 55, key: 'boating-party', cat: 'masters', title: 'Luncheon of the Boating Party', artist: 'Pierre-Auguste Renoir', date: '1880–81', year: 1881, museum: 'phillips' },
  { i: 58, key: 'folies', cat: 'masters', title: 'A Bar at the Folies-Bergère', artist: 'Édouard Manet', date: '1882', year: 1882, museum: 'courtauld' },
  { i: 61, key: 'dance-class', cat: 'masters', title: 'The Dance Class', artist: 'Edgar Degas', date: '1874', year: 1874, museum: 'orsay' },
  { i: 64, key: 'parasol', cat: 'masters', title: 'Woman with a Parasol – Madame Monet and Her Son', artist: 'Claude Monet', date: '1875', year: 1875, museum: 'nga' },
  { i: 70, key: 'hay-wain', cat: 'landscape', title: 'The Hay Wain', artist: 'John Constable', date: '1821', year: 1821, museum: 'ngl' },
  { i: 73, key: 'temeraire', cat: 'sea', title: 'The Fighting Temeraire', artist: 'J. M. W. Turner', date: '1839', year: 1839, museum: 'ngl' },
  { i: 76, key: 'primavera', cat: 'masters', title: 'Primavera', artist: 'Sandro Botticelli', date: 'c. 1480', year: 1480, museum: 'uffizi' },
  { i: 80, key: 'school-athens', cat: 'masters', title: 'The School of Athens', artist: 'Raphael', date: '1509–11', year: 1511, museum: 'vatican' },
  { i: 82, key: 'last-supper', cat: 'masters', title: 'The Last Supper', artist: 'Leonardo da Vinci', date: '1495–98', year: 1498, museum: 'grazie' },
  { i: 85, key: 'bathers-asnieres', cat: 'masters', title: 'Bathers at Asnières', artist: 'Georges Seurat', date: '1884', year: 1884, museum: 'ngl' },
  { i: 88, key: 'seurat-circus', cat: 'people', title: 'The Circus', artist: 'Georges Seurat', date: '1891', year: 1891, museum: 'orsay' },
  { i: 91, key: 'napoleon-alps', cat: 'masters', title: 'Napoleon Crossing the Alps', artist: 'Jacques-Louis David', date: '1801', year: 1801, museum: 'belvedere' },
  { i: 94, key: 'view-delft', cat: 'masters', title: 'View of Delft', artist: 'Johannes Vermeer', date: 'c. 1660–61', year: 1661, museum: 'mauritshuis' },
  { i: 98, key: 'art-of-painting', cat: 'masters', title: 'The Art of Painting', artist: 'Johannes Vermeer', date: 'c. 1666–68', year: 1668, museum: 'khm' },
  { i: 96, key: 'little-street', cat: 'city', title: 'The Little Street', artist: 'Johannes Vermeer', date: 'c. 1658', year: 1658, museum: 'rijks' },
  { i: 101, key: 'harvesters', cat: 'landscape', title: 'The Harvesters', artist: 'Pieter Bruegel the Elder', date: '1565', year: 1565, museum: 'met' },
  { i: 106, key: 'peasant-wedding', cat: 'people', title: 'The Peasant Wedding', artist: 'Pieter Bruegel the Elder', date: '1567', year: 1567, museum: 'khm' },
  { i: 107, key: 'goya-parasol', cat: 'people', title: 'The Parasol', artist: 'Francisco Goya', date: '1777', year: 1777, museum: 'prado' },
  { i: 110, key: 'flaming-june', cat: 'masters', title: 'Flaming June', artist: 'Frederic Leighton', date: '1895', year: 1895, museum: 'ponce' },
  { i: 112, key: 'heliogabalus', cat: 'masters', title: 'The Roses of Heliogabalus', artist: 'Lawrence Alma-Tadema', date: '1888', year: 1888, museum: 'private' },
  { i: 114, key: 'vertumnus', cat: 'portrait', title: 'Vertumnus', artist: 'Giuseppe Arcimboldo', date: '1591', year: 1591, museum: 'skokloster' },
  { i: 119, key: 'storm-galilee', cat: 'sea', title: 'The Storm on the Sea of Galilee', artist: 'Rembrandt van Rijn', date: '1633', year: 1633, museum: 'gardner' },
  { i: 122, key: 'basket-fruit', cat: 'still', title: 'Basket of Fruit', artist: 'Caravaggio', date: 'c. 1599', year: 1599, museum: 'ambrosiana' },
  { i: 127, key: 'bosschaert-bouquet', cat: 'still', title: 'Bouquet of Flowers in a Glass Vase', artist: 'Ambrosius Bosschaert the Elder', date: '1621', year: 1621, museum: 'nga' },
  { i: 128, key: 'ninth-wave', cat: 'sea', title: 'The Ninth Wave', artist: 'Ivan Aivazovsky', date: '1850', year: 1850, museum: 'rusmus' },
  { i: 131, key: 'sorolla-seashore', cat: 'sea', title: 'Strolling along the Seashore', artist: 'Joaquín Sorolla', date: '1909', year: 1909, museum: 'sorolla' },
  { i: 133, key: 'cassatt-boating', cat: 'people', title: 'The Boating Party', artist: 'Mary Cassatt', date: '1893–94', year: 1894, museum: 'nga' },
  { i: 136, key: 'breezing-up', cat: 'sea', title: 'Breezing Up (A Fair Wind)', artist: 'Winslow Homer', date: '1873–76', year: 1876, museum: 'nga' },
  { i: 139, key: 'sierra-nevada', cat: 'landscape', title: 'Among the Sierra Nevada, California', artist: 'Albert Bierstadt', date: '1868', year: 1868, museum: 'saam' },
  { t: 'Cole Thomas The Oxbow (The Connecticut River near Northampton 1836).jpg', key: 'oxbow', cat: 'landscape', title: 'The Oxbow', artist: 'Thomas Cole', date: '1836', year: 1836, museum: 'met' },
  { i: 144, key: 'canaletto-grand-canal', cat: 'city', title: 'The Entrance to the Grand Canal, Venice', artist: 'Canaletto', date: 'c. 1730', year: 1730, museum: 'mfah' },
  { i: 148, key: 'montmartre-night', cat: 'city', title: 'The Boulevard Montmartre at Night', artist: 'Camille Pissarro', date: '1897', year: 1897, museum: 'ngl' },
  { i: 154, key: 'plum-garden', cat: 'ukiyoe', title: 'Plum Garden at Kameido', artist: 'Utagawa Hiroshige', date: '1857', year: 1857, museum: 'cbl' },
  { i: 157, key: 'kajikazawa', cat: 'ukiyoe', title: 'Kajikazawa in Kai Province', artist: 'Katsushika Hokusai', date: 'c. 1830–32', year: 1831, museum: 'met' },
  { i: 159, key: 'audubon-flamingo', cat: 'animal', title: 'American Flamingo', artist: 'John James Audubon', date: '1838', year: 1838, museum: 'audubon' },
  { i: 168, key: 'larsson-breakfast', cat: 'people', title: 'Breakfast under the Big Birch', artist: 'Carl Larsson', date: '1896', year: 1896, museum: 'nmsw' },
  { i: 170, key: 'poppy-field', cat: 'landscape', title: 'Poppy Field', artist: 'Claude Monet', date: '1873', year: 1873, museum: 'orsay' },
  { i: 174, key: 'bougival', cat: 'people', title: 'Dance at Bougival', artist: 'Pierre-Auguste Renoir', date: '1883', year: 1883, museum: 'mfa' },
  { i: 176, key: 'vision-sermon', cat: 'masters', title: 'Vision after the Sermon', artist: 'Paul Gauguin', date: '1888', year: 1888, museum: 'ngs' },
  { i: 179, key: 'sainte-victoire', cat: 'landscape', title: 'Mont Sainte-Victoire Seen from the Bibémus Quarry', artist: 'Paul Cézanne', date: 'c. 1897', year: 1897, museum: 'bma' },
  { i: 182, key: 'dejeuner', cat: 'masters', title: 'Le Déjeuner sur l\'herbe', artist: 'Édouard Manet', date: '1863', year: 1863, museum: 'orsay' },
  { i: 185, key: 'girl-reading', cat: 'masters', title: 'Girl Reading a Letter at an Open Window', artist: 'Johannes Vermeer', date: 'c. 1657–59', year: 1659, museum: 'dresden' },
  { i: 191, key: 'isle-dead', cat: 'landscape', title: 'Isle of the Dead (third version)', artist: 'Arnold Böcklin', date: '1883', year: 1883, museum: 'berlin' },
  { i: 195, key: 'hylas', cat: 'masters', title: 'Hylas and the Nymphs', artist: 'John William Waterhouse', date: '1896', year: 1896, museum: 'manchester' },
  { i: 197, key: 'munch-sun', cat: 'modern', title: 'The Sun', artist: 'Edvard Munch', date: '1911', year: 1911, museum: 'uio' },
  { i: 202, key: 'ejiri', cat: 'ukiyoe', title: 'Ejiri in Suruga Province', artist: 'Katsushika Hokusai', date: 'c. 1830–32', year: 1831, museum: 'met' },
]);
add('masters2', [
  { i: 1, key: 'carnation-lily', cat: 'masters', title: 'Carnation, Lily, Lily, Rose', artist: 'John Singer Sargent', date: '1885–86', year: 1886, museum: 'tate' },
  { i: 5, key: 'blue-armchair', cat: 'people', title: 'Little Girl in a Blue Armchair', artist: 'Mary Cassatt', date: '1878', year: 1878, museum: 'nga' },
  { i: 6, key: 'water-lily-pond', cat: 'landscape', title: 'Bridge over a Pond of Water Lilies', artist: 'Claude Monet', date: '1899', year: 1899, museum: 'met' },
  { i: 9, key: 'sainte-adresse', cat: 'sea', title: 'Garden at Sainte-Adresse', artist: 'Claude Monet', date: '1867', year: 1867, museum: 'met' },
  { i: 13, key: 'umbrellas', cat: 'people', title: 'The Umbrellas', artist: 'Pierre-Auguste Renoir', date: 'c. 1881–86', year: 1886, museum: 'ngl' },
  { i: 15, key: 'night-cafe', cat: 'masters', title: 'The Night Café', artist: 'Vincent van Gogh', date: '1888', year: 1888, museum: 'yale' },
  { i: 18, key: 'beech-grove', cat: 'landscape', title: 'Beech Grove I', artist: 'Gustav Klimt', date: '1902', year: 1902, museum: 'dresdennm' },
  { i: 22, key: 'farm-garden', cat: 'still', title: 'Farm Garden with Sunflowers', artist: 'Gustav Klimt', date: '1907', year: 1907, museum: 'belvedere' },
  { i: 24, key: 'angelus', cat: 'people', title: 'The Angelus', artist: 'Jean-François Millet', date: '1857–59', year: 1859, museum: 'orsay' },
  { i: 27, key: 'laughing-cavalier', cat: 'portrait', title: 'The Laughing Cavalier', artist: 'Frans Hals', date: '1624', year: 1624, museum: 'wallace' },
  { i: 32, key: 'bacchus-ariadne', cat: 'masters', title: 'Bacchus and Ariadne', artist: 'Titian', date: '1520–23', year: 1523, museum: 'ngl' },
  { i: 37, key: 'creation-adam', cat: 'masters', title: 'The Creation of Adam', artist: 'Michelangelo', date: 'c. 1512', year: 1512, museum: 'vatican' },
  { i: 40, key: 'rain-steam-speed', cat: 'landscape', title: 'Rain, Steam and Speed – The Great Western Railway', artist: 'J. M. W. Turner', date: '1844', year: 1844, museum: 'ngl' },
  { i: 44, key: 'san-giorgio', cat: 'city', title: 'San Giorgio Maggiore at Dusk', artist: 'Claude Monet', date: '1908', year: 1908, museum: 'cardiff' },
  { i: 46, key: 'mucha-zodiac', cat: 'poster', title: 'Zodiac', artist: 'Alphonse Mucha', date: '1896', year: 1896, museum: 'private' },
  { i: 144, key: 'mucha-job', cat: 'poster', title: 'Job', artist: 'Alphonse Mucha', date: '1896', year: 1896, museum: 'bnf' },
  { i: 52, key: 'rouen-cathedral', cat: 'city', title: 'Rouen Cathedral, West Façade, Sunlight', artist: 'Claude Monet', date: '1894', year: 1894, museum: 'nga' },
  { i: 56, key: 'watering-can', cat: 'portrait', title: 'A Girl with a Watering Can', artist: 'Pierre-Auguste Renoir', date: '1876', year: 1876, museum: 'nga' },
  { i: 58, key: 'proverbs', cat: 'people', title: 'Netherlandish Proverbs', artist: 'Pieter Bruegel the Elder', date: '1559', year: 1559, museum: 'berlingg' },
  { i: 59, key: 'magpie', cat: 'landscape', title: 'The Magpie', artist: 'Claude Monet', date: '1868–69', year: 1869, museum: 'orsay' },
  { i: 62, key: 'sisley-snow', cat: 'landscape', title: 'Snow at Louveciennes', artist: 'Alfred Sisley', date: '1878', year: 1878, museum: 'orsay' },
  { i: 65, key: 'attersee', cat: 'landscape', title: 'Attersee', artist: 'Gustav Klimt', date: '1900', year: 1900, museum: 'leopold' },
  { i: 69, key: 'composition-vii', cat: 'modern', title: 'Composition VII', artist: 'Wassily Kandinsky', date: '1913', year: 1913, museum: 'tretyakov' },
  { i: 71, key: 'surprised', cat: 'animal', title: 'Surprised! (Tiger in a Tropical Storm)', artist: 'Henri Rousseau', date: '1891', year: 1891, museum: 'ngl' },
  { i: 76, key: 'hida-bridge', cat: 'ukiyoe', title: 'The Suspension Bridge on the Border of Hida and Etchū Provinces', artist: 'Katsushika Hokusai', date: 'c. 1830', year: 1830, museum: 'met' },
  { i: 78, key: 'fishing-boats', cat: 'sea', title: 'Fishing Boats on the Beach at Saintes-Maries', artist: 'Vincent van Gogh', date: '1888', year: 1888, museum: 'vgm' },
  { i: 87, key: 'regatta', cat: 'sea', title: 'Regattas at Argenteuil', artist: 'Claude Monet', date: 'c. 1872', year: 1872, museum: 'orsay' },
  { i: 92, key: 'cradle', cat: 'people', title: 'The Cradle', artist: 'Berthe Morisot', date: '1872', year: 1872, museum: 'orsay' },
  { i: 101, key: 'barge-haulers', cat: 'people', title: 'Barge Haulers on the Volga', artist: 'Ilya Repin', date: '1870–73', year: 1873, museum: 'rusmus' },
  { i: 105, key: 'pine-forest', cat: 'animal', title: 'Morning in a Pine Forest', artist: 'Ivan Shishkin', date: '1889', year: 1889, museum: 'tretyakov' },
  { i: 110, key: 'golden-autumn', cat: 'landscape', title: 'Golden Autumn', artist: 'Isaac Levitan', date: '1895', year: 1895, museum: 'tretyakov' },
  { i: 117, key: 'korin-irises', cat: 'ukiyoe', title: 'Irises at Yatsuhashi (Eight Bridges)', artist: 'Ogata Kōrin', date: 'c. 1710', year: 1710, museum: 'met' },
  { i: 120, key: 'wind-thunder', cat: 'ukiyoe', title: 'Wind God and Thunder God', artist: 'Tawaraya Sōtatsu', date: 'c. 1630', year: 1630, museum: 'kenninji' },
  { i: 121, key: 'three-beauties', cat: 'ukiyoe', title: 'Three Beauties of the Present Day', artist: 'Kitagawa Utamaro', date: 'c. 1793', year: 1793, museum: 'mfa' },
  { i: 129, key: 'koson-crow', cat: 'animal', title: 'Cawing Crow', artist: 'Ohara Koson', date: 'c. 1910', year: 1910, museum: 'commons' },
  { i: 137, key: 'redoute-rose', cat: 'still', title: 'The Roses: China or Bengal Rose', artist: 'Pierre-Joseph Redouté', date: '1817–24', year: 1820, museum: 'cma' },
  { i: 140, key: 'haeckel-actiniae', cat: 'pattern', title: 'Actiniae, from Art Forms in Nature', artist: 'Ernst Haeckel', date: '1904', year: 1904, museum: 'commons' },
  { i: 151, key: 'blind-girl', cat: 'masters', title: 'The Blind Girl', artist: 'John Everett Millais', date: '1856', year: 1856, museum: 'bmag' },
  { i: 154, key: 'proserpine', cat: 'portrait', title: 'Proserpine', artist: 'Dante Gabriel Rossetti', date: '1874', year: 1874, museum: 'tate' },
  { i: 160, key: 'straw-hat', cat: 'portrait', title: 'Self-Portrait in a Straw Hat', artist: 'Élisabeth Vigée Le Brun', date: '1782', year: 1782, museum: 'ngl' },
  { i: 162, key: 'blue-boy', cat: 'portrait', title: 'The Blue Boy', artist: 'Thomas Gainsborough', date: 'c. 1770', year: 1770, museum: 'huntington' },
  { i: 171, key: 'midsummer-dance', cat: 'people', title: 'Midsummer Dance', artist: 'Anders Zorn', date: '1897', year: 1897, museum: 'nmsw' },
  { i: 174, key: 'skagen-evening', cat: 'sea', title: 'Summer Evening on Skagen\'s Southern Beach', artist: 'Peder Severin Krøyer', date: '1893', year: 1893, museum: 'skagen' },
  { i: 176, key: 'hip-hip-hurrah', cat: 'people', title: 'Hip, Hip, Hurrah!', artist: 'Peder Severin Krøyer', date: '1888', year: 1888, museum: 'gothenburg' },
  { i: 181, key: 'hammershoi-interior', cat: 'people', title: 'Interior with a Woman Seen from the Back', artist: 'Vilhelm Hammershøi', date: '1903–04', year: 1904, museum: 'randers' },
]);
// ── 빈티가 사진: 포토크롬 (1890~1910, 미국 의회도서관 소장본 위주, PD)
add('photo', [
  { i: 0, key: 'pc-venice', cat: 'photo', title: 'The Grand Canal, Venice', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 1, key: 'pc-neuschwanstein', cat: 'photo', title: 'Neuschwanstein Castle, Bavaria', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 4, key: 'pc-matterhorn', cat: 'photo', title: 'The Matterhorn after Sunset, from Staffelalp', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 7, key: 'pc-hardanger', cat: 'photo', title: 'Tyssestrengene Falls, Hardanger Fjord, Norway', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 10, key: 'pc-sphinx', cat: 'photo', title: 'The Sphinx and Pyramids, Cairo', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 13, key: 'pc-bosphorus', cat: 'photo', title: 'The Bosphorus from Kuleli, Constantinople', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 20, key: 'pc-niagara', cat: 'photo', title: 'Niagara Falls from the Steel Arch Bridge', artist: 'Photochrom print', date: '1900', year: 1900, museum: 'loc' },
  { i: 21, key: 'pc-yosemite', cat: 'photo', title: 'South Dome, Yosemite Valley', artist: 'Photochrom print', date: '1898', year: 1898, museum: 'loc' },
  { i: 25, key: 'pc-eiffel', cat: 'photo', title: 'The Eiffel Tower and the Trocadéro, Paris Exposition of 1900', artist: 'Photochrom print', date: '1900', year: 1900, museum: 'loc' },
  { i: 27, key: 'pc-tower-bridge', cat: 'photo', title: 'Tower Bridge (open), London', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 35, key: 'pc-rheinstein', cat: 'photo', title: 'Rheinstein Castle on the Rhine', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 43, key: 'pc-yellowstone', cat: 'photo', title: 'The Paint Pot, Yellowstone National Park', artist: 'Photochrom print', date: '1902', year: 1902, museum: 'loc' },
  { i: 45, key: 'pc-colosseum', cat: 'photo', title: 'The Colosseum, Rome', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 48, key: 'pc-vesuvius', cat: 'photo', title: 'Naples and Mount Vesuvius', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 52, key: 'pc-blue-grotto', cat: 'photo', title: 'The Blue Grotto, Capri', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 57, key: 'pc-lucerne', cat: 'photo', title: 'Lake Lucerne from the Bürgenstock', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 60, key: 'pc-edinburgh', cat: 'photo', title: 'Princes Street, Edinburgh', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 64, key: 'pc-moscow', cat: 'photo', title: 'Cathedral of Christ the Saviour, Moscow', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 75, key: 'pc-mont-saint-michel', cat: 'photo', title: 'Mont Saint-Michel from the Causeway', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 78, key: 'pc-amalfi', cat: 'photo', title: 'Amalfi from the Capuchin Monastery', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 86, key: 'pc-chillon', cat: 'photo', title: 'Château de Chillon and the Dents du Midi', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 89, key: 'pc-interlaken', cat: 'photo', title: 'Interlaken and the Jungfrau', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 99, key: 'pc-mostar', cat: 'photo', title: 'The Old Bridge, Mostar', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 115, key: 'pc-ceylon', cat: 'photo', title: 'Buddhist Temple on the Road to Galle, Ceylon', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 117, key: 'pc-madurai', cat: 'photo', title: 'Gopuram of the Meenakshi Temple, Madurai', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 120, key: 'pc-golden-gate', cat: 'photo', title: 'Surf near the Golden Gate, San Francisco', artist: 'Photochrom print', date: '1901', year: 1901, museum: 'loc' },
  { i: 132, key: 'pc-banff', cat: 'photo', title: 'Falls of the Bow River, Banff', artist: 'Photochrom print', date: '1902', year: 1902, museum: 'loc' },
  { i: 138, key: 'pc-havana', cat: 'photo', title: 'San Francisco Wharf, Havana', artist: 'Photochrom print', date: '1904', year: 1904, museum: 'loc' },
  { i: 150, key: 'pc-brussels', cat: 'photo', title: 'Guild Houses on the Grand-Place, Brussels', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 156, key: 'pc-prague', cat: 'photo', title: 'Entrance to Prague Castle', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 165, key: 'pc-innsbruck', cat: 'photo', title: 'The Golden Roof, Innsbruck', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 171, key: 'pc-milan', cat: 'photo', title: 'Piazza del Duomo, Milan', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 174, key: 'pc-pisa', cat: 'photo', title: 'The Leaning Tower, Pisa', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 181, key: 'pc-giralda', cat: 'photo', title: 'La Giralda, Seville', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 185, key: 'pc-alhambra', cat: 'photo', title: 'The Alhambra, Granada', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { i: 210, key: 'pc-loch-katrine', cat: 'photo', title: 'The Pier, Loch Katrine, Trossachs', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
  { t: 'Peking. Summerpalace, Marbleboat LCCN2017658054.jpg', key: 'pc-summer-palace', cat: 'photo', title: 'The Marble Boat, Summer Palace, Peking', artist: 'Photochrom print', date: 'c. 1895', year: 1895, museum: 'loc' },
]);
// ── 우주 (NASA·ESA 공개 이미지, PD 또는 CC BY)
add('space2', [
  { i: 2, key: 'sp-pillars', cat: 'space', title: 'Pillars of Creation (Webb NIRCam)', artist: 'James Webb Space Telescope', date: '2022', year: 2022, museum: 'webb', credit: 'NASA, ESA, CSA, STScI' },
  { i: 4, key: 'sp-cosmic-cliffs', cat: 'space', title: 'Cosmic Cliffs in the Carina Nebula', artist: 'James Webb Space Telescope', date: '2022', year: 2022, museum: 'webb', credit: 'NASA, ESA, CSA, STScI' },
  { i: 7, key: 'sp-crab', cat: 'space', title: 'The Crab Nebula', artist: 'Hubble Space Telescope', date: '2005', year: 2005, museum: 'hubble', credit: 'NASA, ESA, J. Hester and A. Loll (Arizona State University)' },
  { i: 9, key: 'sp-helix', cat: 'space', title: 'The Helix Nebula', artist: 'Hubble Space Telescope', date: '2003', year: 2003, museum: 'hubble', credit: 'NASA, NOAO, ESA, the Hubble Helix Nebula Team' },
  { i: 15, key: 'sp-whirlpool', cat: 'space', title: 'The Whirlpool Galaxy (M51)', artist: 'Hubble Space Telescope', date: '2005', year: 2005, museum: 'hubble', credit: 'NASA, ESA, S. Beckwith (STScI) and the Hubble Heritage Team' },
  { i: 18, key: 'sp-sombrero', cat: 'space', title: 'The Sombrero Galaxy (M104)', artist: 'Hubble Space Telescope', date: '2003', year: 2003, museum: 'hubble', credit: 'NASA and the Hubble Heritage Team (STScI/AURA)' },
  { i: 25, key: 'sp-orion', cat: 'space', title: 'The Orion Nebula', artist: 'Hubble Space Telescope', date: '2006', year: 2006, museum: 'hubble', credit: 'NASA, ESA, M. Robberto (STScI/ESA) and the Hubble Space Telescope Orion Treasury Project Team' },
  { i: 29, key: 'sp-earthrise', cat: 'space', title: 'Earthrise', artist: 'Apollo 8 (William Anders)', date: '1968', year: 1968, museum: 'nasa', credit: 'NASA / Bill Anders' },
  { i: 31, key: 'sp-blue-marble', cat: 'space', title: 'The Blue Marble', artist: 'Apollo 17 crew', date: '1972', year: 1972, museum: 'nasa', credit: 'NASA / Apollo 17' },
  { i: 34, key: 'sp-saturn', cat: 'space', title: 'Saturn at Equinox', artist: 'Cassini spacecraft', date: '2009', year: 2009, museum: 'jpl', credit: 'NASA / JPL / Space Science Institute' },
  { i: 39, key: 'sp-butterfly', cat: 'space', title: 'The Butterfly Nebula (NGC 6302)', artist: 'Hubble Space Telescope', date: '2009', year: 2009, museum: 'hubble', credit: 'NASA, ESA and the Hubble SM4 ERO Team' },
  { i: 45, key: 'sp-lagoon', cat: 'space', title: 'The Lagoon Nebula', artist: 'Hubble Space Telescope', date: '2018', year: 2018, museum: 'hubble', credit: 'NASA, ESA, STScI' },
  { i: 51, key: 'sp-stephans-quintet', cat: 'space', title: "Stephan's Quintet", artist: 'James Webb Space Telescope', date: '2022', year: 2022, museum: 'webb', credit: 'NASA, ESA, CSA, STScI' },
  { i: 56, key: 'sp-cartwheel', cat: 'space', title: 'The Cartwheel Galaxy', artist: 'James Webb Space Telescope', date: '2022', year: 2022, museum: 'webb', credit: 'NASA, ESA, CSA, STScI' },
  { i: 57, key: 'sp-mystic-mountain', cat: 'space', title: 'Mystic Mountain in the Carina Nebula', artist: 'Hubble Space Telescope', date: '2010', year: 2010, museum: 'hubble', credit: 'NASA, ESA, M. Livio and the Hubble 20th Anniversary Team (STScI)' },
  { i: 61, key: 'sp-bubble', cat: 'space', title: 'The Bubble Nebula (NGC 7635)', artist: 'Hubble Space Telescope', date: '2016', year: 2016, museum: 'hubble', credit: 'NASA, ESA, Hubble Heritage Team' },
  { i: 70, key: 'sp-aldrin', cat: 'space', title: 'Buzz Aldrin on the Moon', artist: 'Apollo 11 (Neil Armstrong)', date: '1969', year: 1969, museum: 'nasa', credit: 'NASA / Neil Armstrong' },
  { i: 79, key: 'sp-tarantula', cat: 'space', title: 'The Tarantula Nebula', artist: 'James Webb Space Telescope', date: '2022', year: 2022, museum: 'webb', credit: 'NASA, ESA, CSA, STScI, Webb ERO Production Team' },
  { i: 104, key: 'sp-pluto', cat: 'space', title: 'Pluto in True Color', artist: 'New Horizons spacecraft', date: '2015', year: 2015, museum: 'nasa', credit: 'NASA / Johns Hopkins University APL / Southwest Research Institute' },
  { i: 138, key: 'sp-great-red-spot', cat: 'space', title: "Jupiter's Great Red Spot", artist: 'Juno spacecraft', date: '2017', year: 2017, museum: 'jpl', credit: 'NASA / SwRI / MSSS / Gerald Eichstädt / Seán Doran' },
  { i: 75, key: 'sp-aurora', cat: 'space', title: 'Aurora Australis from the Space Station', artist: 'ISS Expedition 23 crew', date: '2010', year: 2010, museum: 'nasa', credit: 'NASA / ISS Expedition 23' },
  { i: 86, key: 'sp-antennae', cat: 'space', title: 'The Antennae Galaxies', artist: 'Hubble Space Telescope', date: '2006', year: 2006, museum: 'hubble', credit: 'NASA, ESA, and the Hubble Heritage Team (STScI/AURA)' },
  { i: 106, key: 'sp-neptune', cat: 'space', title: 'Neptune', artist: 'Voyager 2', date: '1989', year: 1989, museum: 'jpl', credit: 'NASA / JPL' },
]);
export const PICKS = P;
// ── 해석
const UA = 'jigsawlab-catalog/0.1 (seabow2@nate.com)';
async function byTitle(t) { const d = await (await fetch(`https://commons.wikimedia.org/w/api.php?action=query&titles=${encodeURIComponent('File:' + t)}&prop=imageinfo&iiprop=url|size|mime|extmetadata&iiurlwidth=1600&format=json`, { headers: { 'user-agent': UA } })).json(); const p = Object.values(d.query.pages)[0]; const ii = p.imageinfo[0]; return { title: t, w: ii.width, h: ii.height, lic: ii.extmetadata?.LicenseShortName?.value ?? '', url: ii.url, thumb: ii.thumburl, page: ii.descriptionurl, credit: '' }; }
const sel = []; const keys = new Set();
for (const p of P) {
  const o = p.t ? await byTitle(p.t) : C[p.s]?.[p.i]; if (!o) { console.log('missing', p.s, p.i ?? p.t); continue; }
  if (keys.has(p.key)) { console.log('dup key', p.key); continue; } keys.add(p.key);
  const nasa = !!o.nasaId;
  const license = nasa ? 'Public domain (NASA)' : (o.lic === 'Public domain' ? 'Public domain' : o.lic);
  const big = p.cat === 'photo' && o.thumb ? o.thumb.replace('/1600px-', '/2400px-') : o.thumb; const dl = nasa ? o.url : (o.w > 1600 && big ? big : o.url);
  sel.push({ key: p.key, cat: p.cat, title: p.title, artist: p.artist, date: p.date, year: p.year, medium: p.medium, museum: MUSEUMS[p.museum] ?? [p.museum, p.museum, p.museum], credit: p.credit ?? (nasa ? o.credit : ''), source: o.page, license, dl, file: o.title ?? o.nasaId, w: o.w, h: o.h });
}
writeFileSync('scripts/extra/selected.json', JSON.stringify(sel, null, 1));
const cnt = {}; for (const s of sel) cnt[s.cat] = (cnt[s.cat] || 0) + 1; console.log(sel.length, cnt);
